### ISSUE TITLE
Hidden files and folders not showing in searches?

### ISSUE THREAD

**Issue by pemartins1** [chg-hou/DawnlightSearch#18]
Hidden files and folders are not showing up in my searches.

Here's an example where I search for the Dawnlight Search's ini file but it is not found because it's inside the .config folder:

![printscreen](https://i.imgur.com/MtDj6EV.png)

Tested with DawnlightSearch-0.1.2.5-x86_64.AppImage in Kubuntu 19.04 and MX Linux 18.3.

Is it a bug or is there some option I'm not finding?

And congrats, awesome application!

**Comment by chg-hou** [comment]
Thanks for your feedback. Fixed in commit [e007a5c24bec7379316a57ff8db9f579b4535329](https://github.com/chg-hou/DawnlightSearch/commit/e007a5c24bec7379316a57ff8db9f579b4535329).
The previous filter **QDir::AllEntries|QDir::NoDotAndDotDot** does not include hidden files.
