### ISSUE TITLE
Strange display in names with the same character repeated many times

### ISSUE THREAD

**Issue by pemartins1** [chg-hou/DawnlightSearch#21]
If names with the same character repeated many times, in example "wwwwwwwwwwwww.txt" for a file and "qqqqqqqqqqqqq" for a folder, sometimes the name in the search field is displayed with ">" symbols in the name.

Example printscreens:

![1](https://i.imgur.com/Clr2sed.png)

![2](https://i.imgur.com/GnOxq1B.png)

![3](https://i.imgur.com/KOrflDo.png)

Tested with DawnlightSearch-0.1.2.5-x86_64.AppImage in Kubuntu 19.04.

**Comment by chg-hou** [comment]
Fixed in commit [2bf892e7b60c70708c363d4451914070aed47d3a](https://github.com/chg-hou/DawnlightSearch/commit/2bf892e7b60c70708c363d4451914070aed47d3a).

The **b>** comes from html bold formatting. Made a mistake when the searching text appears more than once.
