### ISSUE TITLE
Appimage not integrating with the system (no desktop file is created)

### ISSUE THREAD

**Issue by pemartins1** [chg-hou/DawnlightSearch#22]
The appimage is not integrating with the system, better said no .desktop file is created so the application is integrated in the system menu.

Many appimages give the option to the user, when ran and not finding a .desktop file for the app, to create one.

Tested with DawnlightSearch-0.1.2.5-x86_64.AppImage in Kubuntu 19.04 and MX Linux 18.3.

**Comment by chg-hou** [comment]
Fixed. Will detect and create .desktop when start at the first time.
