### ISSUE TITLE
Old version 1.2.5 in assets instead of new 1.2.6

### ISSUE THREAD

**Issue by pemartins1** [chg-hou/DawnlightSearch#23]
Not a bug, just a notice that previous version 1.2.5 was put in 1.2.6 assets instead of the new one:

![image](https://i.imgur.com/Nqc4h6M.png)

Thank you very much for the excellent app and thank you very much for all the feedback and bug corrections.

**Comment by chg-hou** [comment]
Thanks. Forgot to update the version string. A new release has been submitted.
