### ISSUE TITLE
[Feature request] Add option (or by default) to always focus on the search box

### ISSUE THREAD

**Issue by pemartins1** [chg-hou/DawnlightSearch#24]
Add option (or by default) to place the focus on the search box every time the Dawnlight Search window is selected, this way it's quicker to perform the search.

So that every time the user clicks on Dawnlight Search's window or starts the application, he just has to start typing.
Currently you have to click on the search box field first.

**Comment by chg-hou** [comment]
Thanks for suggestion. Have added a checkbox in the advanced setting window.
