### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [chg-hou/DawnlightSearch#3]
`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found`

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

Reference:
https://github.com/AppImage/appimage.github.io/pull/616

**Comment by chg-hou** [comment]
@probonopd 
I manually bundle libstdc++.so into /AppDir/usr/lib/ and switch to g++ 4.8 to compile. Now it should work on Ubuntu 14.04.
As it depends on kio-dev which is introduced after 16.04, I have to stick to "dist: xenial".

**Comment by probonopd** [comment]
Thanks @chg-hou but I don't think it will work on 14.04 if you compile it on 16.04, because it will have "too new" dependencies.

**Comment by chg-hou** [comment]
@probonopd 
Forget to mention that I did test it on 14.04. Except icons and KIO part which depend on KF5, other main functions work well. Maybe it don't require quite a lot of new dependencies. Not sure.
![selection_179](https://user-images.githubusercontent.com/12953903/41507388-3b42dece-7264-11e8-8437-271881f993a2.png)

**Comment by probonopd** [comment]
Cool!

**Comment by probonopd** [comment]
Thank you very much, confirmed working on 14.04. Added to https://appimage.github.io/apps/.
